version: "3.2"
services:
  influxdb:
    # image: influxdb:latest
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    ports:
      - "2003:2003"
      - "8086:8086"
    expose:
      - 8086
      - 2003
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      # - INFLUXDB_DB=db0
      # - INFLUXDB_ADMIN_USER=admin
      # - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      # - INFLUXDB_USER=telegraf
      # - INFLUXDB_USER_PASSWORD=secretpassword
      - INFLUXDB_HTTP_LOG_ENABLED=true
    volumes:
      # - "$PWD/influxdb/volume:/var/lib/influxdb"
      - "$PWD/influxdb/volume:/root/.influxdbv2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 30s
      timeout: 10s
      retries: 5
  grafana:
    image: grafana/grafana:7.4.2
    user: "$UID:$GID"
    container_name: grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - "$PWD/grafana/volume:/var/lib/grafana"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
    links:
      - influxdb
  stock-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: stock-app:latest
    container_name: stock-app
    environment:
      - INFLUX-URL=http://influxdb:8086
      - INFLUX-TOKEN=Qja94aR19EopLmK5RAr-u5m3v59EKe_T4Ft6rLa7SiDNqRPbQDi74ytaSY4S3-NXovXk8vJxRaewPZCcCelbEA==
      - INFLUX-ORG=test
      - INFLUX-BUCKET=stock
      - ALPHA-URL=https://www.alphavantage.co/query?outputsize=full&function=TIME_SERIES_DAILY&symbol={symbol}&apikey={alpha_api_key}
      - ALPHA-API-KEY=2IX3H2UPE39MNJF6
      - SYMBOLS=AAPL,ABNB,AMZN,GOOGL,MSFT,NET,NFLX,PINS,REGI,NIO,TSLA
      - LAST-DATA=True
      - CONFIG-FILE=/usr/src/app/conf/conf.json
    volumes:
      - "./app/volume:/usr/src/app/conf"
    restart: on-failure
    depends_on:
      - grafana
      - influxdb
    links:
      - grafana
      - influxdb
networks:
  default:
    external:
      name: stock-network
